apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: fqts
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJmcXRzMDEuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogIlpHOWphMlZ5WTNKbFpITTZRV0pqWkVBeE1qTTAiCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson